### ISSUE TITLE
Support places with spaces it in

### ISSUE THREAD

**Issue by Cedrick84** [artemy/alfred-ns-schedule#3]
Hey there, 

Nice plugin. However I can't seem to find how to search for places like "Den Haag" that have spaces in it. Could you either add it to the guide if it exists or add some functionality that provides this?

**Comment by artemy** [comment]
@Cedrick84 thanks for this suggestion. I've made an update so you can use `_` (underscore) instead of space inside the name, e.g. for trains between Den Haag Centraal and Amsterdam Bijlmer Arena you can type `den_haag_centraal amsterdam_bijlmer_arena`

**Comment by Cedrick84** [comment]
that's amazing thanks so much!

**Comment by artemy** [comment]
Fixed in release [v3.1](https://github.com/artemy/alfred-ns-schedule/releases/tag/v3.1)
