### ISSUE TITLE
Trim API key

### ISSUE THREAD

**Issue by artemy** [artemy/alfred-ns-schedule#5]
Based on the feedback from Alfred forum, it might be useful to trim the API key to remove whitespace characters around it

**Comment by vitorgalvao** [comment]
This seems to be done too, the trimming checkbox is checked in the configuration.

**Comment by artemy** [comment]
well spotted, @vitorgalvao 
fixed in [v3.0](https://github.com/artemy/alfred-ns-schedule/releases/tag/v3.0)
